name: Deploy Super Mario to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  TF_WORKING_DIR: ./mario-game/terr-config
  KUBE_CONFIG: /home/runner/.kube/config

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      # Install Terraform
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y wget gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform -y
          terraform -version

      # Initialize Terraform
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      # Apply Terraform
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply --auto-approve

      # Update kubeconfig to connect kubectl with EKS
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name EKS_CLOUD \
            --region ${{ env.AWS_REGION }}

      # Deploy Kubernetes manifests
      - name: Deploy Super Mario Game to EKS
        working-directory: ./mario-game
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml

      # Optional: Show Service Info
      - name: Show Service Details
        run: kubectl describe service mario-service
